# https://www.authlete.com/developers/ciba/implement_ciba_with_authlete/

###
# @name processCIBARequest
# https://docs.authlete.com/en/shared/latest#post-/api/-serviceId-/backchannel/authentication
POST {{baseUrl}}/api/backchannel/authentication
Authorization: Basic {{apiKey}}:{{apiSecret}}
Content-Type: application/json

{
    "clientId": "{{clientId}}",
    "clientSecret": "{{clientSecret}}",
    "parameters": "login_hint=john&scope=openid&client_notification_token=my-client-notification-token&user_code=my-user-code"
}

###
# @name issueCIBAAuthenctication
# https://docs.authlete.com/en/shared/latest#post-/api/-serviceId-/backchannel/authentication/issue
POST {{baseUrl}}/api/backchannel/authentication/issue
Authorization: Basic {{apiKey}}:{{apiSecret}}
Content-Type: application/json


{
    "ticket": "{{processCIBARequest.response.body.ticket}}"
}

###
# @name completeCIBAAuthentication
# https://docs.authlete.com/en/shared/latest#post-/api/-serviceId-/backchannel/authentication/complete
###
POST {{baseUrl}}/api/backchannel/authentication/complete
Authorization: Basic {{apiKey}}:{{apiSecret}}
Content-Type: application/json

{ 
    "ticket": "{{processCIBARequest.response.body.ticket}}", 
    "result": "AUTHORIZED", 
    "subject": "john" 
}


###
# @name failCIBAAuthenticationRequest
# https://docs.authlete.com/en/shared/latest#post-/api/-serviceId-/backchannel/authentication/complete
# 
# The reason of the failure of the backchannel authentication request. This request parameter is not mandatory but optional. However, giving this parameter is recommended. If omitted, SERVER_ERROR is used as a reason.
# Allowed: ACCESS_DENIED┃EXPIRED_LOGIN_HINT_TOKEN┃INVALID_BINDING_MESSAGE┃INVALID_TARGET┃INVALID_USER_CODE┃MISSING_USER_CODE┃SERVER_ERROR┃UNAUTHORIZED_CLIENT┃UNKNOWN_USER_ID
POST {{baseUrl}}/api/backchannel/authentication/fail
Authorization: Basic {{apiKey}}:{{apiSecret}}
Content-Type: application/json

{ 
    "ticket": "{{processCIBARequest.response.body.ticket}}", 
    "reason": "ACCESS_DENIED"
}

###
# @name tokenRequest
# If you use the CIBA flow with Poll mode, you can use the following request to get the access token.
POST {{baseUrl}}/api/auth/token
Authorization: Basic {{apiKey}}:{{apiSecret}}
Content-Type: application/json

{ 
    "parameters": "grant_type=urn:openid:params:grant-type:ciba&auth_req_id={{completeCIBAAuthenticationRequest.response.body.authReqId}}", 
    "clientId": "{{clientId}}",
    "clientSecret": "{{clientSecret}}"
}
